//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSAA_Project3.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSAA_Project3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_1_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_1_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_1_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_1_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_2_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_2_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_2_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_2_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_3_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_3_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_3_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_3_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_4_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_4_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_4_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_4_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_5_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_5_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_5_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_5_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Down {
            get {
                object obj = ResourceManager.GetObject("Arrow_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Left {
            get {
                object obj = ResourceManager.GetObject("Arrow_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Right {
            get {
                object obj = ResourceManager.GetObject("Arrow_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Up {
            get {
                object obj = ResourceManager.GetObject("Arrow_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;GraphEdgeCollection&gt;
        ///  
        ///  &lt;Edge id=&quot;1&quot; v1=&quot;Dorm21&quot; v2=&quot;SHos&quot; len=&quot;550&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;2&quot; v1=&quot;SHos&quot; v2=&quot;Dorm1&quot; len=&quot;180&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;3&quot; v1=&quot;BGMt&quot; v2=&quot;ColArt&quot; len=&quot;300&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;4&quot; v1=&quot;ColArt&quot; v2=&quot;YSq&quot; len=&quot;100&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;5&quot; v1=&quot;YSq&quot; v2=&quot;ColPE&quot; len=&quot;100&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;6&quot; v1=&quot;ColPE&quot; v2=&quot;SWGate&quot; len=&quot;180&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;7&quot; v1=&quot;CAE&quot; v2=&quot;Lib&quot; len=&quot;200&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edge id=&quot;8&quot; v1=&quot;Lib&quot; v2=&quot;TBd1&quot; len=&quot;150&quot;&gt;&lt;/Edge&gt;
        ///  &lt;Edg [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Green {
            get {
                object obj = ResourceManager.GetObject("Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Locations&gt;
        ///  
        ///  &lt;loc Type=&quot;生活&quot;&gt;
        ///    &lt;Code&gt;Dorm21&lt;/Code&gt;
        ///    &lt;Name&gt;二十一舍&lt;/Name&gt;
        ///    &lt;EngName&gt;Dorm. #21&lt;/EngName&gt;
        ///    &lt;Intro&gt;&lt;/Intro&gt;
        ///    &lt;ImgAdd&gt;&lt;/ImgAdd&gt;
        ///  &lt;/loc&gt;
        ///
        ///  &lt;loc Type=&quot;生活&quot;&gt;
        ///    &lt;Code&gt;SHos&lt;/Code&gt;
        ///    &lt;Name&gt;校医院&lt;/Name&gt;
        ///    &lt;EngName&gt;Hospital&lt;/EngName&gt;
        ///    &lt;Intro&gt;&lt;/Intro&gt;
        ///    &lt;ImgAdd&gt;Hos&lt;/ImgAdd&gt;
        ///  &lt;/loc&gt;
        ///
        ///  &lt;loc Type=&quot;生活&quot;&gt;
        ///    &lt;Code&gt;Dorm1&lt;/Code&gt;
        ///    &lt;Name&gt;一舍&lt;/Name&gt;
        ///    &lt;EngName&gt;Dorm. #1&lt;/EngName&gt;
        ///    &lt;Intro&gt;&lt;/Intro&gt;
        ///    &lt;ImgAdd&gt;Dorm1&lt;/ImgA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LocationDBNew {
            get {
                return ResourceManager.GetString("LocationDBNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Metro {
            get {
                object obj = ResourceManager.GetObject("Metro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Metro_HighRes {
            get {
                object obj = ResourceManager.GetObject("Metro_HighRes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Metro_LowRes {
            get {
                object obj = ResourceManager.GetObject("Metro_LowRes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Metro_New {
            get {
                object obj = ResourceManager.GetObject("Metro_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Purple {
            get {
                object obj = ResourceManager.GetObject("Purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Red {
            get {
                object obj = ResourceManager.GetObject("Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Road {
            get {
                object obj = ResourceManager.GetObject("Road", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Station {
            get {
                object obj = ResourceManager.GetObject("Station", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Station_End {
            get {
                object obj = ResourceManager.GetObject("Station_End", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Station_Start {
            get {
                object obj = ResourceManager.GetObject("Station_Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   按资源名称查找
        /// </summary>
        internal static System.Drawing.Bitmap FindImg(string name)
        {
            object obj = ResourceManager.GetObject(name, resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
